# Spotify Music Analytics — Exploratory Data Analysis

This notebook contains the exploratory data analysis of the processed Spotify datasets.

Datasets:
- artists
- albums
- tracks

## 1. Imports

In [10]:
import pandas as pd

## 2. Load processed datasets

In [11]:
artists = pd.read_csv("../data/processed/artists.csv")
albums = pd.read_csv("../data/processed/albums.csv")
tracks = pd.read_csv("../data/processed/tracks.csv")

## 3. Dataset overview

In [12]:
print("Artists:", artists.shape)
print("Albums:", albums.shape)
print("Tracks:", tracks.shape)

Artists: (5, 4)
Albums: (93, 7)
Tracks: (1566, 13)

## 4. Sample records

In [5]:
artists.head()

,spotify_id,name,type,spotify_url
0,7dGJo4pcD2V6oG8kP0tJRR,Eminem,artist,https://open.spotify.com/artist/7dGJo4pcD2V6oG...
1,6XyY86QOPPrYVGvF9ch6wz,Linkin Park,artist,https://open.spotify.com/artist/6XyY86QOPPrYVG...
2,0k17h0D3J5VfsdmQ1iZtE9,Pink Floyd,artist,https://open.spotify.com/artist/0k17h0D3J5Vfsd...
3,0WwSkZ7LtFUFjGjMZBMt6T,Dire Straits,artist,https://open.spotify.com/artist/0WwSkZ7LtFUFjG...
4,0ECwFtbIWEVNwjlrfc6xoL,Eagles,artist,https://open.spotify.com/artist/0ECwFtbIWEVNwj...

In [6]:
albums.head()

,spotify_id,name,artist_id,artist_name,album_type,total_tracks,spotify_url
0,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,12,https://open.spotify.com/album/5DV2liMHX5AqtiL...
1,2DQ6hHlAGj6DiT0Y068bnK,The Marshall Mathers LP (25th Anniversary),7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,20,https://open.spotify.com/album/2DQ6hHlAGj6DiT0...
2,31hcgCSu4mlA82syOFItur,The Death of Slim Shady (Coup De Grâce): Expan...,7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,23,https://open.spotify.com/album/31hcgCSu4mlA82s...
3,3kjHLu1pL7tdY88GFwEkl6,The Death of Slim Shady (Coup De Grâce),7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,19,https://open.spotify.com/album/3kjHLu1pL7tdY88...
4,5EUgcfO5OWxnniHR3QYFcK,The Marshall Mathers LP2 (Expanded Edition),7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,27,https://open.spotify.com/album/5EUgcfO5OWxnniH...

In [7]:
tracks.head()

,spotify_id,name,album_id,album_name,artist_id,artist_name,disc_number,track_number,duration_ms,explicit,spotify_url,duration_seconds,duration_minutes
0,0TR2EOv4irt7GAiLIZ3kZ8,Stan,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,1,404106,True,https://open.spotify.com/track/0TR2EOv4irt7GAi...,404.106,6.73510
1,3VvxblbhUGyyBgdT7EQR0p,Bad Guy,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,2,434358,True,https://open.spotify.com/track/3VvxblbhUGyyBgd...,434.358,7.23930
2,773Ls0jOd52jEzWh6Pc55U,Arose,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,3,274626,True,https://open.spotify.com/track/773Ls0jOd52jEzW...,274.626,4.57710
3,2hejwnTsNazjgnLFxnwvbF,Beautiful,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,4,392826,True,https://open.spotify.com/track/2hejwnTsNazjgnL...,392.826,6.54710
4,5lRcJDTuiLWQe0OkWNIfVS,Not Afraid,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,5,248133,True,https://open.spotify.com/track/5lRcJDTuiLWQe0O...,248.133,4.13555

## 5. Dataset structure

In [8]:
artists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   spotify_id   5 non-null      object
 1   name         5 non-null      object
 2   type         5 non-null      object
 3   spotify_url  5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

In [9]:
albums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   spotify_id    93 non-null     object
 1   name          93 non-null     object
 2   artist_id     93 non-null     object
 3   artist_name   93 non-null     object
 4   album_type    93 non-null     object
 5   total_tracks  93 non-null     int64
 6   spotify_url   93 non-null     object
dtypes: int64(1), object(6)
memory usage: 5.2+ KB

In [10]:
tracks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1566 entries, 0 to 1565
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   spotify_id        1566 non-null   object
 1   name              1566 non-null   object
 2   album_id          1566 non-null   object
 3   album_name        1566 non-null   object
 4   artist_id         1566 non-null   object
 5   artist_name       1566 non-null   object
 6   disc_number       1566 non-null   int64
 7   track_number      1566 non-null   int64
 8   duration_ms       1566 non-null   int64
 9   explicit          1566 non-null   bool
 10  spotify_url       1566 non-null   object
 11  duration_seconds  1566 non-null   float64
 12  duration_minutes  1566 non-null   float64
dtypes: bool(1), float64(2), int64(3), object(7)
memory usage: 148.5+ KB

## 6. Summary

In [11]:
summary = pd.DataFrame(
    {
        "dataset": ["artists", "albums", "tracks"],
        "rows": [
            len(artists),
            len(albums),
            len(tracks),
        ],
        "columns": [
            artists.shape[1],
            albums.shape[1],
            tracks.shape[1],
        ],
    }
)

summary

   dataset  rows  columns
0  artists     5        4
1   albums    93        7
2   tracks  1566       13

## 7. Descriptive statistics

In [12]:
tracks[
    [
        "disc_number",
        "track_number",
        "duration_ms",
        "duration_seconds",
        "duration_minutes",
    ]
].describe()

,disc_number,track_number,duration_ms,duration_seconds,duration_minutes
count,1566.000000,1566.000000,1.566000e+03,1566.000000,1566.000000
mean,1.411239,8.170498,2.618929e+05,261.892922,4.364882
std,0.978086,5.697120,1.468631e+05,146.863104,2.447718
min,1.000000,1.000000,1.002600e+04,10.026000,0.167100
25%,1.000000,4.000000,1.919405e+05,191.940500,3.199008
50%,1.000000,7.000000,2.430995e+05,243.099500,4.051658
75%,1.000000,11.000000,3.085728e+05,308.572750,5.142879
max,6.000000,38.000000,1.525826e+06,1525.826000,25.430433

In [13]:
duration_summary = pd.Series(
    {
        "average_minutes": tracks["duration_minutes"].mean(),
        "median_minutes": tracks["duration_minutes"].median(),
        "minimum_minutes": tracks["duration_minutes"].min(),
        "maximum_minutes": tracks["duration_minutes"].max(),
    }
)

duration_summary

average_minutes     4.364882
median_minutes      4.051658
minimum_minutes     0.167100
maximum_minutes    25.430433
dtype: float64

In [14]:
dataset_counts = pd.Series(
    {
        "artists": len(artists),
        "albums": len(albums),
        "tracks": len(tracks),
    }
)

dataset_counts

artists       5
albums       93
tracks     1566
dtype: int64

In [15]:
explicit_counts = tracks["explicit"].value_counts()

explicit_counts

explicit
False    1097
True      469
Name: count, dtype: int64

In [16]:
explicit_percentage = (
    tracks["explicit"]
    .value_counts(normalize=True)
    .mul(100)
)

explicit_percentage

explicit
False    70.051086
True     29.948914
Name: proportion, dtype: float64

In [17]:
albums_per_artist = (
    albums.groupby("artist_name")
    .size()
    .sort_values(ascending=False)
)

albums_per_artist

artist_name
Linkin Park     26
Pink Floyd      25
Eminem          20
Eagles          12
Dire Straits    10
dtype: int64

In [18]:
tracks_per_artist = (
    tracks.groupby("artist_name")
    .size()
    .sort_values(ascending=False)
)

tracks_per_artist

artist_name
Linkin Park     518
Eminem          441
Pink Floyd      317
Eagles          186
Dire Straits    104
dtype: int64

In [19]:
total_duration_per_artist = (
    tracks.groupby("artist_name")["duration_minutes"]
    .sum()
    .sort_values(ascending=False)
)

total_duration_per_artist

artist_name
Linkin Park     1791.039833
Pink Floyd      1785.298350
Eminem          1746.397217
Eagles           838.890917
Dire Straits     673.778950
Name: duration_minutes, dtype: float64

In [20]:
overview = pd.Series(
    {
        "total_artists": len(artists),
        "total_albums": len(albums),
        "total_tracks": len(tracks),
        "average_track_duration_min": tracks["duration_minutes"].mean(),
        "median_track_duration_min": tracks["duration_minutes"].median(),
        "explicit_tracks": tracks["explicit"].sum(),
        "explicit_percentage": tracks["explicit"].mean() * 100,
    }
)

overview

total_artists                    5.000000
total_albums                    93.000000
total_tracks                  1566.000000
average_track_duration_min       4.364882
median_track_duration_min        4.051658
explicit_tracks                469.000000
explicit_percentage             29.948914
dtype: float64

## 8. Artist-level analysis

In [13]:
artist_analysis = (
    tracks.groupby("artist_name")
    .agg(
        total_tracks=("spotify_id", "count"),
        average_duration_min=("duration_minutes", "mean"),
        median_duration_min=("duration_minutes", "median"),
        total_duration_min=("duration_minutes", "sum"),
        explicit_tracks=("explicit", "sum"),
    )
    .reset_index()
)

In [14]:
albums_by_artist = (
    albums.groupby("artist_name")
    .size()
    .reset_index(name="total_albums")
)

In [15]:
artist_analysis = artist_analysis.merge(
    albums_by_artist,
    on="artist_name",
    how="left",
)

In [17]:
artist_analysis["explicit_percentage"] = (
    artist_analysis["explicit_tracks"]
    / artist_analysis["total_tracks"]
    * 100
)

In [18]:
artist_analysis = artist_analysis[
    [
        "artist_name",
        "total_albums",
        "total_tracks",
        "average_duration_min",
        "median_duration_min",
        "total_duration_min",
        "explicit_tracks",
        "explicit_percentage",
    ]
]

In [19]:
artist_analysis = artist_analysis.sort_values(
    by="total_tracks",
    ascending=False,
)

artist_analysis

,artist_name,total_albums,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
3,Linkin Park,26,518,3.457606,3.421108,1791.039833,45,8.687259
2,Eminem,20,441,3.960084,4.389300,1746.397217,410,92.970522
4,Pink Floyd,25,317,5.631856,4.996433,1785.298350,13,4.100946
1,Eagles,12,186,4.510166,4.370442,838.890917,0,0.000000
0,Dire Straits,10,104,6.478644,5.667442,673.778950,1,0.961538

In [20]:
artist_analysis.sort_values(
    by="average_duration_min",
    ascending=False,
)

,artist_name,total_albums,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
0,Dire Straits,10,104,6.478644,5.667442,673.778950,1,0.961538
4,Pink Floyd,25,317,5.631856,4.996433,1785.298350,13,4.100946
1,Eagles,12,186,4.510166,4.370442,838.890917,0,0.000000
2,Eminem,20,441,3.960084,4.389300,1746.397217,410,92.970522
3,Linkin Park,26,518,3.457606,3.421108,1791.039833,45,8.687259

In [21]:
artist_analysis.sort_values(
    by="explicit_percentage",
    ascending=False,
)

,artist_name,total_albums,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
2,Eminem,20,441,3.960084,4.389300,1746.397217,410,92.970522
3,Linkin Park,26,518,3.457606,3.421108,1791.039833,45,8.687259
4,Pink Floyd,25,317,5.631856,4.996433,1785.298350,13,4.100946
0,Dire Straits,10,104,6.478644,5.667442,673.778950,1,0.961538
1,Eagles,12,186,4.510166,4.370442,838.890917,0,0.000000

In [22]:
artist_analysis.sort_values(
    by="total_duration_min",
    ascending=False,
)

,artist_name,total_albums,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
3,Linkin Park,26,518,3.457606,3.421108,1791.039833,45,8.687259
4,Pink Floyd,25,317,5.631856,4.996433,1785.298350,13,4.100946
2,Eminem,20,441,3.960084,4.389300,1746.397217,410,92.970522
1,Eagles,12,186,4.510166,4.370442,838.890917,0,0.000000
0,Dire Straits,10,104,6.478644,5.667442,673.778950,1,0.961538