# Spotify Music Analytics — Exploratory Data Analysis

This notebook contains the exploratory data analysis of the processed Spotify datasets.

Datasets:
- artists
- albums
- tracks

## 1. Imports

In [10]:
import pandas as pd

## 2. Load processed datasets

In [11]:
artists = pd.read_csv("../data/processed/artists.csv")
albums = pd.read_csv("../data/processed/albums.csv")
tracks = pd.read_csv("../data/processed/tracks.csv")

## 3. Dataset overview

In [12]:
print("Artists:", artists.shape)
print("Albums:", albums.shape)
print("Tracks:", tracks.shape)

Artists: (5, 4)
Albums: (93, 7)
Tracks: (1566, 13)

## 4. Sample records

In [5]:
artists.head()

,spotify_id,name,type,spotify_url
0,7dGJo4pcD2V6oG8kP0tJRR,Eminem,artist,https://open.spotify.com/artist/7dGJo4pcD2V6oG...
1,6XyY86QOPPrYVGvF9ch6wz,Linkin Park,artist,https://open.spotify.com/artist/6XyY86QOPPrYVG...
2,0k17h0D3J5VfsdmQ1iZtE9,Pink Floyd,artist,https://open.spotify.com/artist/0k17h0D3J5Vfsd...
3,0WwSkZ7LtFUFjGjMZBMt6T,Dire Straits,artist,https://open.spotify.com/artist/0WwSkZ7LtFUFjG...
4,0ECwFtbIWEVNwjlrfc6xoL,Eagles,artist,https://open.spotify.com/artist/0ECwFtbIWEVNwj...

In [6]:
albums.head()

,spotify_id,name,artist_id,artist_name,album_type,total_tracks,spotify_url
0,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,12,https://open.spotify.com/album/5DV2liMHX5AqtiL...
1,2DQ6hHlAGj6DiT0Y068bnK,The Marshall Mathers LP (25th Anniversary),7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,20,https://open.spotify.com/album/2DQ6hHlAGj6DiT0...
2,31hcgCSu4mlA82syOFItur,The Death of Slim Shady (Coup De Grâce): Expan...,7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,23,https://open.spotify.com/album/31hcgCSu4mlA82s...
3,3kjHLu1pL7tdY88GFwEkl6,The Death of Slim Shady (Coup De Grâce),7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,19,https://open.spotify.com/album/3kjHLu1pL7tdY88...
4,5EUgcfO5OWxnniHR3QYFcK,The Marshall Mathers LP2 (Expanded Edition),7dGJo4pcD2V6oG8kP0tJRR,Eminem,album,27,https://open.spotify.com/album/5EUgcfO5OWxnniH...

In [7]:
tracks.head()

,spotify_id,name,album_id,album_name,artist_id,artist_name,disc_number,track_number,duration_ms,explicit,spotify_url,duration_seconds,duration_minutes
0,0TR2EOv4irt7GAiLIZ3kZ8,Stan,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,1,404106,True,https://open.spotify.com/track/0TR2EOv4irt7GAi...,404.106,6.73510
1,3VvxblbhUGyyBgdT7EQR0p,Bad Guy,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,2,434358,True,https://open.spotify.com/track/3VvxblbhUGyyBgd...,434.358,7.23930
2,773Ls0jOd52jEzWh6Pc55U,Arose,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,3,274626,True,https://open.spotify.com/track/773Ls0jOd52jEzW...,274.626,4.57710
3,2hejwnTsNazjgnLFxnwvbF,Beautiful,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,4,392826,True,https://open.spotify.com/track/2hejwnTsNazjgnL...,392.826,6.54710
4,5lRcJDTuiLWQe0OkWNIfVS,Not Afraid,5DV2liMHX5AqtiLqy3Qu1b,STANS (The Official Soundtrack),7dGJo4pcD2V6oG8kP0tJRR,Eminem,1,5,248133,True,https://open.spotify.com/track/5lRcJDTuiLWQe0O...,248.133,4.13555

## 5. Dataset structure

In [8]:
artists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   spotify_id   5 non-null      object
 1   name         5 non-null      object
 2   type         5 non-null      object
 3   spotify_url  5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

In [9]:
albums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   spotify_id    93 non-null     object
 1   name          93 non-null     object
 2   artist_id     93 non-null     object
 3   artist_name   93 non-null     object
 4   album_type    93 non-null     object
 5   total_tracks  93 non-null     int64
 6   spotify_url   93 non-null     object
dtypes: int64(1), object(6)
memory usage: 5.2+ KB

In [10]:
tracks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1566 entries, 0 to 1565
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   spotify_id        1566 non-null   object
 1   name              1566 non-null   object
 2   album_id          1566 non-null   object
 3   album_name        1566 non-null   object
 4   artist_id         1566 non-null   object
 5   artist_name       1566 non-null   object
 6   disc_number       1566 non-null   int64
 7   track_number      1566 non-null   int64
 8   duration_ms       1566 non-null   int64
 9   explicit          1566 non-null   bool
 10  spotify_url       1566 non-null   object
 11  duration_seconds  1566 non-null   float64
 12  duration_minutes  1566 non-null   float64
dtypes: bool(1), float64(2), int64(3), object(7)
memory usage: 148.5+ KB

## 6. Summary

In [11]:
summary = pd.DataFrame(
    {
        "dataset": ["artists", "albums", "tracks"],
        "rows": [
            len(artists),
            len(albums),
            len(tracks),
        ],
        "columns": [
            artists.shape[1],
            albums.shape[1],
            tracks.shape[1],
        ],
    }
)

summary

   dataset  rows  columns
0  artists     5        4
1   albums    93        7
2   tracks  1566       13

## 7. Descriptive statistics

In [12]:
tracks[
    [
        "disc_number",
        "track_number",
        "duration_ms",
        "duration_seconds",
        "duration_minutes",
    ]
].describe()

,disc_number,track_number,duration_ms,duration_seconds,duration_minutes
count,1566.000000,1566.000000,1.566000e+03,1566.000000,1566.000000
mean,1.411239,8.170498,2.618929e+05,261.892922,4.364882
std,0.978086,5.697120,1.468631e+05,146.863104,2.447718
min,1.000000,1.000000,1.002600e+04,10.026000,0.167100
25%,1.000000,4.000000,1.919405e+05,191.940500,3.199008
50%,1.000000,7.000000,2.430995e+05,243.099500,4.051658
75%,1.000000,11.000000,3.085728e+05,308.572750,5.142879
max,6.000000,38.000000,1.525826e+06,1525.826000,25.430433

In [13]:
duration_summary = pd.Series(
    {
        "average_minutes": tracks["duration_minutes"].mean(),
        "median_minutes": tracks["duration_minutes"].median(),
        "minimum_minutes": tracks["duration_minutes"].min(),
        "maximum_minutes": tracks["duration_minutes"].max(),
    }
)

duration_summary

average_minutes     4.364882
median_minutes      4.051658
minimum_minutes     0.167100
maximum_minutes    25.430433
dtype: float64

In [14]:
dataset_counts = pd.Series(
    {
        "artists": len(artists),
        "albums": len(albums),
        "tracks": len(tracks),
    }
)

dataset_counts

artists       5
albums       93
tracks     1566
dtype: int64

In [15]:
explicit_counts = tracks["explicit"].value_counts()

explicit_counts

explicit
False    1097
True      469
Name: count, dtype: int64

In [16]:
explicit_percentage = (
    tracks["explicit"]
    .value_counts(normalize=True)
    .mul(100)
)

explicit_percentage

explicit
False    70.051086
True     29.948914
Name: proportion, dtype: float64

In [17]:
albums_per_artist = (
    albums.groupby("artist_name")
    .size()
    .sort_values(ascending=False)
)

albums_per_artist

artist_name
Linkin Park     26
Pink Floyd      25
Eminem          20
Eagles          12
Dire Straits    10
dtype: int64

In [18]:
tracks_per_artist = (
    tracks.groupby("artist_name")
    .size()
    .sort_values(ascending=False)
)

tracks_per_artist

artist_name
Linkin Park     518
Eminem          441
Pink Floyd      317
Eagles          186
Dire Straits    104
dtype: int64

In [19]:
total_duration_per_artist = (
    tracks.groupby("artist_name")["duration_minutes"]
    .sum()
    .sort_values(ascending=False)
)

total_duration_per_artist

artist_name
Linkin Park     1791.039833
Pink Floyd      1785.298350
Eminem          1746.397217
Eagles           838.890917
Dire Straits     673.778950
Name: duration_minutes, dtype: float64

In [20]:
overview = pd.Series(
    {
        "total_artists": len(artists),
        "total_albums": len(albums),
        "total_tracks": len(tracks),
        "average_track_duration_min": tracks["duration_minutes"].mean(),
        "median_track_duration_min": tracks["duration_minutes"].median(),
        "explicit_tracks": tracks["explicit"].sum(),
        "explicit_percentage": tracks["explicit"].mean() * 100,
    }
)

overview

total_artists                    5.000000
total_albums                    93.000000
total_tracks                  1566.000000
average_track_duration_min       4.364882
median_track_duration_min        4.051658
explicit_tracks                469.000000
explicit_percentage             29.948914
dtype: float64

## 8. Artist-level analysis

In [13]:
artist_analysis = (
    tracks.groupby("artist_name")
    .agg(
        total_tracks=("spotify_id", "count"),
        average_duration_min=("duration_minutes", "mean"),
        median_duration_min=("duration_minutes", "median"),
        total_duration_min=("duration_minutes", "sum"),
        explicit_tracks=("explicit", "sum"),
    )
    .reset_index()
)

In [14]:
albums_by_artist = (
    albums.groupby("artist_name")
    .size()
    .reset_index(name="total_albums")
)

In [15]:
artist_analysis = artist_analysis.merge(
    albums_by_artist,
    on="artist_name",
    how="left",
)

In [17]:
artist_analysis["explicit_percentage"] = (
    artist_analysis["explicit_tracks"]
    / artist_analysis["total_tracks"]
    * 100
)

In [18]:
artist_analysis = artist_analysis[
    [
        "artist_name",
        "total_albums",
        "total_tracks",
        "average_duration_min",
        "median_duration_min",
        "total_duration_min",
        "explicit_tracks",
        "explicit_percentage",
    ]
]

In [19]:
artist_analysis = artist_analysis.sort_values(
    by="total_tracks",
    ascending=False,
)

artist_analysis

,artist_name,total_albums,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
3,Linkin Park,26,518,3.457606,3.421108,1791.039833,45,8.687259
2,Eminem,20,441,3.960084,4.389300,1746.397217,410,92.970522
4,Pink Floyd,25,317,5.631856,4.996433,1785.298350,13,4.100946
1,Eagles,12,186,4.510166,4.370442,838.890917,0,0.000000
0,Dire Straits,10,104,6.478644,5.667442,673.778950,1,0.961538

In [20]:
artist_analysis.sort_values(
    by="average_duration_min",
    ascending=False,
)

,artist_name,total_albums,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
0,Dire Straits,10,104,6.478644,5.667442,673.778950,1,0.961538
4,Pink Floyd,25,317,5.631856,4.996433,1785.298350,13,4.100946
1,Eagles,12,186,4.510166,4.370442,838.890917,0,0.000000
2,Eminem,20,441,3.960084,4.389300,1746.397217,410,92.970522
3,Linkin Park,26,518,3.457606,3.421108,1791.039833,45,8.687259

In [21]:
artist_analysis.sort_values(
    by="explicit_percentage",
    ascending=False,
)

,artist_name,total_albums,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
2,Eminem,20,441,3.960084,4.389300,1746.397217,410,92.970522
3,Linkin Park,26,518,3.457606,3.421108,1791.039833,45,8.687259
4,Pink Floyd,25,317,5.631856,4.996433,1785.298350,13,4.100946
0,Dire Straits,10,104,6.478644,5.667442,673.778950,1,0.961538
1,Eagles,12,186,4.510166,4.370442,838.890917,0,0.000000

In [22]:
artist_analysis.sort_values(
    by="total_duration_min",
    ascending=False,
)

,artist_name,total_albums,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
3,Linkin Park,26,518,3.457606,3.421108,1791.039833,45,8.687259
4,Pink Floyd,25,317,5.631856,4.996433,1785.298350,13,4.100946
2,Eminem,20,441,3.960084,4.389300,1746.397217,410,92.970522
1,Eagles,12,186,4.510166,4.370442,838.890917,0,0.000000
0,Dire Straits,10,104,6.478644,5.667442,673.778950,1,0.961538

## 9. Track duration analysis

In [23]:
tracks["duration_minutes"].describe()

count    1566.000000
mean        4.364882
std         2.447718
min         0.167100
25%         3.199008
50%         4.051658
75%         5.142879
max        25.430433
Name: duration_minutes, dtype: float64

In [24]:
shortest_tracks = (
    tracks[
        [
            "name",
            "artist_name",
            "album_name",
            "duration_minutes",
        ]
    ]
    .sort_values(
        by="duration_minutes",
        ascending=True,
    )
    .head(10)
)

shortest_tracks

,name,artist_name,album_name,duration_minutes
614,[Stef],Linkin Park,Hybrid Theory (20th Anniversary Edition),0.167100
939,[Stef],Linkin Park,Reanimation,0.167100
406,Paul - Skit,Eminem,The Marshall Mathers LP,0.176667
15,Paul - Skit,Eminem,The Marshall Mathers LP (25th Anniversary),0.176667
498,Foreword,Linkin Park,Meteora 20th Anniversary Edition,0.223100
908,Foreword,Linkin Park,Meteora (Bonus Edition),0.224000
165,Stepdad - Intro,Eminem,Music To Be Murdered By - Side B (Deluxe Edition),0.252667
185,Stepdad - Intro,Eminem,Music To Be Murdered By,0.252667
425,Paul - Skit,Eminem,The Slim Shady LP,0.264000
153,Thus Far - Interlude,Eminem,Music To Be Murdered By - Side B (Deluxe Edition),0.272583

In [25]:
longest_tracks = (
    tracks[
        [
            "name",
            "artist_name",
            "album_name",
            "duration_minutes",
        ]
    ]
    .sort_values(
        by="duration_minutes",
        ascending=False,
    )
    .head(10)
)

longest_tracks

,name,artist_name,album_name,duration_minutes
972,"Shine On You Crazy Diamond - Pts. 1-9, New Ste...",Pink Floyd,Wish You Were Here 50,25.430433
1224,Atom Heart Mother,Pink Floyd,Atom Heart Mother,23.695333
1223,Echoes,Pink Floyd,Meddle,23.555100
988,Echoes - Live from the Los Angeles Sports Aren...,Pink Floyd,Wish You Were Here 50,22.435550
1326,Tunnel Of Love - San Antonio Live In 85,Dire Straits,Brothers In Arms (40th Anniversary),19.440667
967,Shine On You Crazy Diamond - Early Instrumenta...,Pink Floyd,Wish You Were Here 50,18.888217
1179,Dogs - 2018 Remix,Pink Floyd,Animals (2018 Remix),17.113100
1174,Dogs,Pink Floyd,Animals,17.080883
1346,"Tunnel Of Love - Live At Hammersmith Odeon, Lo...",Dire Straits,Alchemy: Dire Straits Live,14.490000
1350,Telegraph Road,Dire Straits,Love Over Gold,14.302217

In [26]:
duration_bins = pd.cut(
    tracks["duration_minutes"],
    bins=[
        0,
        2,
        3,
        4,
        5,
        7,
        float("inf"),
    ],
    labels=[
        "< 2 min",
        "2–3 min",
        "3–4 min",
        "4–5 min",
        "5–7 min",
        "> 7 min",
    ],
    right=False,
)

duration_distribution = (
    duration_bins
    .value_counts()
    .sort_index()
)

duration_distribution

duration_minutes
< 2 min    174
2–3 min    144
3–4 min    443
4–5 min    366
5–7 min    307
> 7 min    132
Name: count, dtype: int64

In [27]:
duration_distribution_percentage = (
    duration_bins
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
)

duration_distribution_percentage

duration_minutes
< 2 min    11.111111
2–3 min     9.195402
3–4 min    28.288633
4–5 min    23.371648
5–7 min    19.604087
> 7 min     8.429119
Name: proportion, dtype: float64

In [28]:
duration_by_artist = (
    tracks.groupby("artist_name")["duration_minutes"]
    .agg(
        [
            "count",
            "mean",
            "median",
            "std",
            "min",
            "max",
        ]
    )
    .sort_values(
        by="mean",
        ascending=False,
    )
)

duration_by_artist

              count      mean    median       std       min        max
artist_name
Dire Straits    104  6.478644  5.667442  2.849016  2.986667  19.440667
Pink Floyd      317  5.631856  4.996433  3.824440  0.512217  25.430433
Eagles          186  4.510166  4.370442  1.580052  0.565333  10.284000
Eminem          441  3.960084  4.389300  1.649475  0.176667   7.239300
Linkin Park     518  3.457606  3.421108  1.230929  0.167100  12.741717

In [29]:
q1 = tracks["duration_minutes"].quantile(0.25)
q3 = tracks["duration_minutes"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

lower_bound, upper_bound

(np.float64(0.2832020833333333), np.float64(8.058685416666666))

In [30]:
duration_outliers = tracks[
    (tracks["duration_minutes"] < lower_bound)
    | (tracks["duration_minutes"] > upper_bound)
][
    [
        "name",
        "artist_name",
        "album_name",
        "duration_minutes",
    ]
].sort_values(
    by="duration_minutes",
    ascending=False,
)

duration_outliers

,name,artist_name,album_name,duration_minutes
972,"Shine On You Crazy Diamond - Pts. 1-9, New Ste...",Pink Floyd,Wish You Were Here 50,25.430433
1224,Atom Heart Mother,Pink Floyd,Atom Heart Mother,23.695333
1223,Echoes,Pink Floyd,Meddle,23.555100
988,Echoes - Live from the Los Angeles Sports Aren...,Pink Floyd,Wish You Were Here 50,22.435550
1326,Tunnel Of Love - San Antonio Live In 85,Dire Straits,Brothers In Arms (40th Anniversary),19.440667
...,...,...,...,...
498,Foreword,Linkin Park,Meteora 20th Anniversary Edition,0.223100
406,Paul - Skit,Eminem,The Marshall Mathers LP,0.176667
15,Paul - Skit,Eminem,The Marshall Mathers LP (25th Anniversary),0.176667
614,[Stef],Linkin Park,Hybrid Theory (20th Anniversary Edition),0.167100
939,[Stef],Linkin Park,Reanimation,0.167100

In [31]:
len(duration_outliers)

97

In [32]:
duration_analysis_summary = pd.Series(
    {
        "average_duration_min": tracks["duration_minutes"].mean(),
        "median_duration_min": tracks["duration_minutes"].median(),
        "standard_deviation_min": tracks["duration_minutes"].std(),
        "shortest_track_min": tracks["duration_minutes"].min(),
        "longest_track_min": tracks["duration_minutes"].max(),
        "q1": q1,
        "q3": q3,
        "iqr": iqr,
        "lower_outlier_bound": lower_bound,
        "upper_outlier_bound": upper_bound,
        "outlier_count": len(duration_outliers),
    }
)

duration_analysis_summary

average_duration_min       4.364882
median_duration_min        4.051658
standard_deviation_min     2.447718
shortest_track_min         0.167100
longest_track_min         25.430433
q1                         3.199008
q3                         5.142879
iqr                        1.943871
lower_outlier_bound        0.283202
upper_outlier_bound        8.058685
outlier_count             97.000000
dtype: float64

## 10. Explicit content analysis

In [33]:
explicit_summary = (
    tracks["explicit"]
    .value_counts()
    .rename_axis("explicit")
    .reset_index(name="track_count")
)

explicit_summary

   explicit  track_count
0     False         1097
1      True          469

In [34]:
explicit_summary["percentage"] = (
    explicit_summary["track_count"]
    / explicit_summary["track_count"].sum()
    * 100
)

explicit_summary

   explicit  track_count  percentage
0     False         1097   70.051086
1      True          469   29.948914

In [35]:
explicit_by_artist = (
    tracks.groupby("artist_name")
    .agg(
        total_tracks=("spotify_id", "count"),
        explicit_tracks=("explicit", "sum"),
    )
    .reset_index()
)

In [36]:
explicit_by_artist["non_explicit_tracks"] = (
    explicit_by_artist["total_tracks"]
    - explicit_by_artist["explicit_tracks"]
)

In [37]:
explicit_by_artist["explicit_percentage"] = (
    explicit_by_artist["explicit_tracks"]
    / explicit_by_artist["total_tracks"]
    * 100
)

In [38]:
explicit_by_artist = explicit_by_artist.sort_values(
    by="explicit_percentage",
    ascending=False,
)

explicit_by_artist

,artist_name,total_tracks,explicit_tracks,non_explicit_tracks,explicit_percentage
2,Eminem,441,410,31,92.970522
3,Linkin Park,518,45,473,8.687259
4,Pink Floyd,317,13,304,4.100946
0,Dire Straits,104,1,103,0.961538
1,Eagles,186,0,186,0.000000

In [40]:
duration_by_explicit = (
    tracks.groupby("explicit")["duration_minutes"]
    .agg(
        [
            "count",
            "mean",
            "median",
            "std",
            "min",
            "max",
        ]
    )
)

duration_by_explicit

          count      mean    median       std       min        max
explicit
False      1097  4.512658  3.929333  2.675613  0.167100  25.430433
True        469  4.019230  4.216000  1.760362  0.176667  13.822883

In [41]:
explicit_artist_duration = (
    tracks.groupby(
        [
            "artist_name",
            "explicit",
        ]
    )["duration_minutes"]
    .agg(
        track_count="count",
        average_duration_min="mean",
        median_duration_min="median",
    )
    .reset_index()
)

explicit_artist_duration

,artist_name,explicit,track_count,average_duration_min,median_duration_min
0,Dire Straits,False,103,6.459774,5.583333
1,Dire Straits,True,1,8.422217,8.422217
2,Eagles,False,186,4.510166,4.370442
3,Eminem,False,31,3.946941,4.493550
4,Eminem,True,410,3.961078,4.368758
5,Linkin Park,False,473,3.433850,3.411683
6,Linkin Park,True,45,3.707303,3.642433
7,Pink Floyd,False,304,5.590698,4.928433
8,Pink Floyd,True,13,6.594321,5.244433

In [42]:
explicit_analysis_summary = pd.Series(
    {
        "total_tracks": len(tracks),
        "explicit_tracks": tracks["explicit"].sum(),
        "non_explicit_tracks": (~tracks["explicit"]).sum(),
        "explicit_percentage": tracks["explicit"].mean() * 100,
        "non_explicit_percentage": (
            (~tracks["explicit"]).mean() * 100
        ),
        "average_explicit_duration_min": tracks.loc[
            tracks["explicit"],
            "duration_minutes",
        ].mean(),
        "average_non_explicit_duration_min": tracks.loc[
            ~tracks["explicit"],
            "duration_minutes",
        ].mean(),
    }
)

explicit_analysis_summary

total_tracks                         1566.000000
explicit_tracks                       469.000000
non_explicit_tracks                  1097.000000
explicit_percentage                    29.948914
non_explicit_percentage                70.051086
average_explicit_duration_min           4.019230
average_non_explicit_duration_min       4.512658
dtype: float64

## 11. Album-level analysis

In [47]:
album_analysis = (
    tracks.groupby(
        [
            "album_id",
            "album_name",
            "artist_name",
        ]
    )
    .agg(
        total_tracks=("spotify_id", "count"),
        average_duration_min=("duration_minutes", "mean"),
        median_duration_min=("duration_minutes", "median"),
        total_duration_min=("duration_minutes", "sum"),
        explicit_tracks=("explicit", "sum"),
    )
    .reset_index()
)

album_analysis

,album_id,album_name,artist_name,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks
0,00BBpx0gG4KfQtxSJBPKUZ,Obscured by Clouds,Pink Floyd,10,4.052505,4.202658,40.525050,0
1,04ZCu8OHFUgbf9Ko0bOSZ2,Eagles Live,Eagles,15,5.045742,5.277100,75.686133,0
2,09WBxbis5Sixt01FVMs8UM,Desperado (2013 Remaster),Eagles,11,3.248608,3.343267,35.734683,0
3,0F77QekrNe8vVAjU2sepja,One of These Nights (2013 Remaster),Eagles,9,4.780607,4.683067,43.025467,0
4,0U6ldwLBEMkwgfQRY4V6D2,Revival,Eminem,19,4.092579,4.246000,77.759000,18
...,...,...,...,...,...,...,...,...
88,7gk5j9Ok764TbTsmkxthYt,On Every Street,Dire Straits,12,5.019772,5.013550,60.237267,0
89,7h2OEj0ifXb3UdgvTmCqfY,Relapse,Eminem,20,3.812538,4.315108,76.250767,18
90,7pgs38iLfEqUtwgCRgvbND,Minutes to Midnight,Linkin Park,14,3.546424,3.417883,49.649933,3
91,7qKEQkRXySP0rhjtXJksfg,From Zero: A Cappellas + Instrumentals,Linkin Park,21,2.906329,3.087233,61.032917,2
92,7qRKpkP0jSOlBMLYZhAMCh,LIVING THINGS: Acapellas and Instrumentals,Linkin Park,22,3.109171,3.090142,68.401767,0

In [48]:
# percentual de faixas explicit por álbum

album_analysis["explicit_percentage"] = (
    album_analysis["explicit_tracks"]
    / album_analysis["total_tracks"]
    * 100
)

In [ ]:
album_analysis = album_analysis[
    [
        "album_id",
        "album_name",
        "artist_name",
        "total_tracks",
        "average_duration_min",
        "median_duration_min",
        "total_duration_min",
        "explicit_tracks",
        "explicit_percentage",
    ]
]

1. Álbuns com mais faixas

In [49]:
albums_with_most_tracks = (
    album_analysis.sort_values(
        by="total_tracks",
        ascending=False,
    )
    .head(10)
)

albums_with_most_tracks

,album_id,album_name,artist_name,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
42,3Q9wXhEAX7NYCPP0hxIuDz,Meteora 20th Anniversary Edition,Linkin Park,89,3.382925,3.344817,301.080350,7,7.865169
22,28DUZ0itKISf2sr6hlseMy,Hybrid Theory (20th Anniversary Edition),Linkin Park,80,3.321651,3.381442,265.732083,1,1.250000
76,6EzbFdrwvWpnpUjzrR57aU,The Eminem Show (Expanded Edition),Eminem,38,4.054766,4.723542,154.081117,29,76.315789
41,3MKvhQoFSrR2PrxXXBHe9B,Music To Be Murdered By - Side B (Deluxe Edition),Eminem,36,3.254015,3.432008,117.144550,36,100.000000
55,4N9EiC0CRRh8CQMBepM3p7,Live From The Forum MMXVIII,Eagles,33,4.174993,4.372000,137.774767,0,0.000000
45,3jlnaVYWc3QEqwCtdYCDS7,Wish You Were Here 50,Pink Floyd,30,8.627349,6.338992,258.820467,4,13.333333
87,7MZzYkbHL9Tk3O6WeD4Z0Z,Relapse: Refill,Eminem,29,4.108353,4.636000,119.142250,27,93.103448
66,5EUgcfO5OWxnniHR3QYFcK,The Marshall Mathers LP2 (Expanded Edition),Eminem,27,4.883048,4.816383,131.842283,22,81.481481
65,5Dbax7G8SWrP9xyzkOvy2F,The Wall,Pink Floyd,26,3.116258,3.250775,81.022717,0,0.000000
19,1uSpngQgBBgwRFYS5sOdqI,Pulse (Live),Pink Floyd,25,6.203248,6.598667,155.081200,1,4.000000

2. Álbuns com maior duração total

In [50]:
longest_albums = (
    album_analysis.sort_values(
        by="total_duration_min",
        ascending=False,
    )
    .head(10)
)

longest_albums

,album_id,album_name,artist_name,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
42,3Q9wXhEAX7NYCPP0hxIuDz,Meteora 20th Anniversary Edition,Linkin Park,89,3.382925,3.344817,301.080350,7,7.865169
22,28DUZ0itKISf2sr6hlseMy,Hybrid Theory (20th Anniversary Edition),Linkin Park,80,3.321651,3.381442,265.732083,1,1.250000
45,3jlnaVYWc3QEqwCtdYCDS7,Wish You Were Here 50,Pink Floyd,30,8.627349,6.338992,258.820467,4,13.333333
83,6vgyxZaH5eLASSqm36uAcL,Brothers In Arms (40th Anniversary),Dire Straits,24,7.466901,6.847217,179.205633,0,0.000000
19,1uSpngQgBBgwRFYS5sOdqI,Pulse (Live),Pink Floyd,25,6.203248,6.598667,155.081200,1,4.000000
76,6EzbFdrwvWpnpUjzrR57aU,The Eminem Show (Expanded Edition),Eminem,38,4.054766,4.723542,154.081117,29,76.315789
32,2lK80Nb29iqCzaRiERvNDS,Delicate Sound of Thunder (2019 Remix) [Live],Pink Floyd,23,6.125472,6.281767,140.885850,0,0.000000
55,4N9EiC0CRRh8CQMBepM3p7,Live From The Forum MMXVIII,Eagles,33,4.174993,4.372000,137.774767,0,0.000000
66,5EUgcfO5OWxnniHR3QYFcK,The Marshall Mathers LP2 (Expanded Edition),Eminem,27,4.883048,4.816383,131.842283,22,81.481481
79,6RVw8oon6nUEbHSy3CZDLr,One of These Nights (Deluxe Edition),Eagles,25,5.044779,4.859967,126.119483,0,0.000000

3. Álbuns com maior duração média por faixa

In [51]:
albums_with_longest_average_tracks = (
    album_analysis.sort_values(
        by="average_duration_min",
        ascending=False,
    )
    .head(10)
)

albums_with_longest_average_tracks

,album_id,album_name,artist_name,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
28,2cUpAOlQjV5uSjkWj5bEQY,Atom Heart Mother,Pink Floyd,5,10.416437,5.473100,52.082183,0,0.000000
7,0bCAjiUamIFqKJsekOYuRw,Wish You Were Here,Pink Floyd,5,8.843773,7.511767,44.218867,0,0.000000
45,3jlnaVYWc3QEqwCtdYCDS7,Wish You Were Here 50,Pink Floyd,30,8.627349,6.338992,258.820467,4,13.333333
86,7JLiApdEm6DhYEdK3cop0v,Alchemy: Dire Straits Live,Dire Straits,11,8.551853,7.582667,94.070383,0,0.000000
5,0Unhg884FzoZhVWyrMvtAG,Animals (2018 Remix),Pink Floyd,5,8.363593,10.291550,41.817967,1,20.000000
44,3b4E89rxzZQ9zkhgKpj8N4,Animals,Pink Floyd,5,8.338883,10.315550,41.694417,1,20.000000
60,4hJqOIahWodpSJU6uDgjvN,Love Over Gold,Dire Straits,5,8.225907,6.764883,41.129533,0,0.000000
10,0ptvgHrZARlAZFmbg0WvDI,Pink Floyd at Pompeii - MCMLXXII (2025 Mix),Pink Floyd,11,8.044670,6.626567,88.491367,0,0.000000
70,5JZxCVMYJqplJhJgfytng2,Live at Knebworth 1990,Pink Floyd,7,7.959326,7.790433,55.715283,0,0.000000
50,468ZwCchVtzEbt9BHmXopb,Meddle,Pink Floyd,6,7.797478,5.571333,46.784867,0,0.000000

4. Álbuns com menor duração média

In [52]:
albums_with_shortest_average_tracks = (
    album_analysis.sort_values(
        by="average_duration_min",
        ascending=True,
    )
    .head(10)
)

albums_with_shortest_average_tracks

,album_id,album_name,artist_name,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
20,1x6p39FFIESOq8q8B4oQXN,From Zero: A Cappellas,Linkin Park,11,2.705292,2.959733,29.758217,2,18.181818
8,0f7R0jf0pcTb6K6IVVPcMD,Meteora (Bonus Edition),Linkin Park,16,2.879202,3.027992,46.067233,0,0.000000
91,7qKEQkRXySP0rhjtXJksfg,From Zero: A Cappellas + Instrumentals,Linkin Park,21,2.906329,3.087233,61.032917,2,9.523810
56,4R6FV9NSzhPihHR0h4pI93,From Zero,Linkin Park,11,2.906865,3.090233,31.975517,2,18.181818
72,5QfFvOMOJ0CrIDmu33RmSJ,From Zero (Deluxe Edition),Linkin Park,14,2.984054,3.132008,41.776750,2,14.285714
11,0vE6mttRTBXRe9rKghyr1l,The Slim Shady LP,Eminem,20,2.990440,3.611108,59.808800,18,90.000000
25,2NbO8RRVTVEUjHaxUVdMDT,Reanimation,Linkin Park,20,3.053717,3.525217,61.074333,1,5.000000
57,4XHIjbhjRmqWlosjj5rqSI,LIVING THINGS,Linkin Park,12,3.088125,3.421000,37.057500,0,0.000000
12,0yU7VItpGPmPcvKmwLg0JT,The Endless River,Pink Floyd,21,3.100069,2.629333,65.101450,0,0.000000
92,7qRKpkP0jSOlBMLYZhAMCh,LIVING THINGS: Acapellas and Instrumentals,Linkin Park,22,3.109171,3.090142,68.401767,0,0.000000

5. Distribuição do número de faixas por álbum

In [53]:
album_track_count_summary = (
    album_analysis["total_tracks"]
    .describe()
)

album_track_count_summary

count    93.000000
mean     16.838710
std      12.348464
min       5.000000
25%      10.000000
50%      14.000000
75%      20.000000
max      89.000000
Name: total_tracks, dtype: float64

6. Comparação de álbuns por artista

In [54]:
album_stats_by_artist = (
    album_analysis.groupby("artist_name")
    .agg(
        total_albums=("album_id", "count"),
        average_tracks_per_album=("total_tracks", "mean"),
        average_album_duration_min=("total_duration_min", "mean"),
        average_track_duration_min=(
            "average_duration_min",
            "mean",
        ),
    )
    .sort_values(
        by="average_album_duration_min",
        ascending=False,
    )
)

album_stats_by_artist

,total_albums,average_tracks_per_album,average_album_duration_min,average_track_duration_min
artist_name,,,,
Eminem,20,22.050000,87.319861,3.988504
Pink Floyd,25,12.680000,71.411934,5.969535
Eagles,12,15.500000,69.907576,4.454366
Linkin Park,26,19.923077,68.886147,3.508778
Dire Straits,10,10.400000,67.377895,6.351977

7. Álbuns com maior percentual explicit

In [55]:
albums_by_explicit_percentage = (
    album_analysis.sort_values(
        by=[
            "explicit_percentage",
            "total_tracks",
        ],
        ascending=[
            False,
            False,
        ],
    )
    .head(10)
)

albums_by_explicit_percentage

,album_id,album_name,artist_name,total_tracks,average_duration_min,median_duration_min,total_duration_min,explicit_tracks,explicit_percentage
41,3MKvhQoFSrR2PrxXXBHe9B,Music To Be Murdered By - Side B (Deluxe Edition),Eminem,36,3.254015,3.432008,117.144550,36,100.000000
17,1kTlYbs28MXw7hwO0NLYif,Encore (Deluxe Version),Eminem,23,3.880893,4.424667,89.260550,23,100.000000
75,6DN7GcZF1HywzrkGN6Eeqk,The Marshall Mathers LP2 (Deluxe),Eminem,21,4.880698,4.890383,102.494650,21,100.000000
29,2cWBwpqMsDJC1ZUwz813lo,The Eminem Show,Eminem,20,3.875428,4.654000,77.508567,20,100.000000
61,4otkd9As6YaxxEkIjXPiZ6,Music To Be Murdered By,Eminem,20,3.228017,3.345992,64.560333,20,100.000000
16,1gUI4keDXbeSil6rwY9qUm,Recovery (Deluxe Edition),Eminem,19,4.554708,4.644000,86.539450,19,100.000000
46,3kjHLu1pL7tdY88GFwEkl6,The Death of Slim Shady (Coup De Grâce),Eminem,19,3.400975,3.836650,64.618517,19,100.000000
51,47BiFcV59TQi2s9SkBo2pb,Recovery,Eminem,17,4.533550,4.644000,77.070350,17,100.000000
38,31hcgCSu4mlA82syOFItur,The Death of Slim Shady (Coup De Grâce): Expan...,Eminem,23,3.386141,3.836650,77.881250,22,95.652174
4,0U6ldwLBEMkwgfQRY4V6D2,Revival,Eminem,19,4.092579,4.246000,77.759000,18,94.736842

In [56]:
# Validating album track counts with Spotify data
album_track_validation = album_analysis.merge(
    albums[
        [
            "spotify_id",
            "total_tracks",
        ]
    ],
    left_on="album_id",
    right_on="spotify_id",
    how="left",
    suffixes=(
        "_collected",
        "_spotify",
    ),
)

album_track_validation["track_count_difference"] = (
    album_track_validation["total_tracks_collected"]
    - album_track_validation["total_tracks_spotify"]
)

album_track_validation[
    album_track_validation["track_count_difference"] != 0
]

Empty DataFrame
Columns: [album_id, album_name, artist_name, total_tracks_collected, average_duration_min, median_duration_min, total_duration_min, explicit_tracks, explicit_percentage, spotify_id, total_tracks_spotify, track_count_difference]
Index: []

In [ ]:
album_analysis_summary = pd.Series(
    {
        "total_albums": len(album_analysis),
        "average_tracks_per_album": (
            album_analysis["total_tracks"].mean()
        ),
        "median_tracks_per_album": (
            album_analysis["total_tracks"].median()
        ),
        "average_album_duration_min": (
            album_analysis["total_duration_min"].mean()
        ),
        "median_album_duration_min": (
            album_analysis["total_duration_min"].median()
        ),
        "largest_album_track_count": (
            album_analysis["total_tracks"].max()
        ),
        "longest_album_duration_min": (
            album_analysis["total_duration_min"].max()
        ),
    }
)

album_analysis_summary